[package]
name = "p2p-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
nokhwa = { version = "0.10", features = ["input-v4l", "input-msmf", "input-avfoundation"] }
image = "0.24"
terminal_size = "0.3"
viuer = "0.9.2"
termimage = "1.2.2"
